### ISSUE TITLE
PHP 7.2 and OneLogin Saml and mcrypt: update to onelogin/php-saml v3

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-realme#24] opened 2018-07-03 02:40 UTC
### Overview
onelogin/php-saml uses mcrypt, which is deprecated in PHP 7.1 and removed in PHP 7.2.

It looks like version 3.x of this library has addressed this issue: https://github.com/onelogin/php-saml/issues/255

We will need to update it at some stage.

### Versions affected
This change needs to be made on both the 2.x and 3.x line for SS3 and SS4 compatibility.

## Pull requests

SS4:
- [x] https://github.com/silverstripe/silverstripe-realme/pull/45

SS3:
- [x] https://github.com/silverstripe/silverstripe-realme/pull/53

**Comment by ScopeyNZ** [comment] 2018-07-03 21:44
This will probably need #17 as a prerequisite.

**Comment by brynwhyman** [comment] 2018-07-04 23:15
Noting that at the time of writing this, we're still waiting for the 3.0 release to be tagged.

**Comment by ScopeyNZ** [comment] 2018-11-08 01:57
The library author has now tagged a 3.0.0 of php-saml

**Comment by chillu** [comment] 2019-03-05 19:59
@brynwhyman We'd like to set PHP 7.3 as the default on new projects in our platforms, and this is the last thing in supported modules which could throw a spanner in the works. My current take is that we set a PHP 7.3 default, and in the unlikely case that RealMe is required on that stack, we'll downgrade accordingly. But would be great if we can claim full PHP 7.3 compatiblity with supported modules soon, right?

**Comment by ScopeyNZ** [comment] 2019-03-05 20:17
Path for getting to 7.3:

- Complete #17 - Investigate why a custom SAML fork was used - investigate whether the upstream repo has resolved whatever concern that was
- Upgrade to the latest version of php-saml and update code with new APIs (if applicable)
- Test with RealMe MTS

**Comment by madmatt** [comment] 2019-03-05 20:24
We can definitely test #17 again now - the issue is that logon and assert endpoints were throwing different XML signatures - one that was valid and one that wasn't. We've also found that the signature has changed recently, meaning we needed to re-fix that code too, so I'd rather remove it and get rid of the fork if possible.

There shouldn't be too much that we need to fix when upgrading `onelogin/php-saml`, it's a pretty stable module all things considered.

@ScopeyNZ Can you add `Test with RealMe ITE` to your list as well? MTS and ITE are very different environments (in particular, the reason for #17 only manifests on ITE and Prod, not MTS).

**Comment by sminnee** [comment] 2019-03-18 21:57
FYI we'll probably need to make this work for CWP 1.9 as well...

**Comment by torleif** [comment] 2019-05-03 02:48
Any updates on this issue? we're running hybridauth, which uses onelogin/php-saml 3.\*. 

it seems like #17 is working on some environments, so it would be nice to have this fix in at least a dev release

**Comment by madmatt** [comment] 2019-05-10 03:59
Yeah we upgraded the silverstripe/saml module as part of the upgrade of that module to SS4 IIRC.

At this stage, if anyone wants to commit to doing the work that'd be awesome, but I'm not likely to have time in the near future to do this, and I don't have any upcoming projects using RealMe that I could justify spending a bit of time on this.

I'll try to take a look on our next company hackday, but I usually don't get to participate in those because of meetings and other urgent work, so it's a slim chance unfortunately.

The actual changes required should be pretty minimal, it's just a single commit that would need to be forward-ported to php-saml v3, it's just the testing that makes it difficult (ideally would be tested against at least MTS and ITE, ideally against Prod as well, as all 3 systems have in the past exhibited different behaviours when returning SAML assertions).

**Comment by chillu** [comment] 2019-06-11 03:18
PHP 7.1 is EOL in Dec 2019, so we really want to recommend to any users of this module to upgrade straight to PHP 7.2 or PHP 7.3 (upgrades are expensive and should be minimised). Which to me raises the priority of this issue. Currently we either ask <PHP 7.1 users to hold off until we support PHP 7.2 fully, or we'll ask them to do twice the upgrade work.

**Comment by brynwhyman** [comment] 2019-06-18 02:48
Expect that our team at SSltd will have time to look at this issue in the coming quarter, ending in August

**Comment by NightJar** [comment] 2019-08-28 22:41
PR https://github.com/silverstripe/silverstripe-realme/pull/45

**Comment by brynwhyman** [comment] 2019-10-11 00:31
Reopening. This hasn't been done for the SS3 line

**Comment by brynwhyman** [comment] 2019-10-16 01:04
Noting that we'll need the SS3 change done before 12 November to include the changes in the CWP quarterly audit, cc @NightJar

**Comment by brynwhyman** [comment] 2020-01-27 23:24
The SS3 PR has been merged, so closing this issue. There's a somewhat related PR to address issues that were uncovered during testing: https://github.com/silverstripe/silverstripe-realme/pull/55

**Closed by brynwhyman** 2020-01-27 23:24 UTC
Labels: affects/v3, affects/v4, change/minor, effort/medium, impact/high, type/enhancement
